Kate E: homework 4 done
eugene-okulik/kate_win pull request #3
Opened 2024-07-12 13:51 UTC by katerinaev

2024-07-12 15:17 UTC, eugene-okulik requested changes
Всё отлично, но проверку на внимательность не прошла

2024-07-12 15:17 UTC, eugene-okulik commented on homework/kate_evtihevich/homework_4/task.py
> +my_dict['dict']['i am a tuple'] = 'Tuple'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-07-12 17:55 UTC, katerinaev commented on homework/kate_evtihevich/homework_4/task.py
> +my_dict['dict']['i am a tuple'] = 'Tuple'
Интересно, сколько внимательных было за историю курса? )))

2024-07-13 10:08 UTC, eugene-okulik approved these changes

2024-07-13 10:10 UTC, eugene-okulik requested changes

2024-07-13 10:10 UTC, eugene-okulik commented on homework/kate_evtihevich/homework_4/task.py
> +my_dict['dict'][('i am a tuple',)] = {1: True }
Осталось только поправить ошибки, найденные линтом. Здесь у тебя лишний пробел перед последней фигурной скобкой.

2024-07-13 10:24 UTC, eugene-okulik approved these changes

2024-07-13 10:27 UTC, eugene-okulik approved these changes

2024-07-13 10:27 UTC, eugene-okulik commented on homework/kate_evtihevich/homework_4/task.py
> +             8: 'Tuple',}
Эту запятую ты зачем-то добавила и теперь линт просит поставить после нее пробел )))

2024-07-13 10:28 UTC, eugene-okulik requested changes
Не пометил как "requested changes", исправляюсь

2024-07-13 10:35 UTC, eugene-okulik approved these changes

2024-07-13 10:35 UTC, merged